name: Cloudflare DDNS Update

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-dns:
    runs-on: [self-hosted, linux]
    if: >
      "${{ secrets.LAST_KNOWN_IP }}" != "${{ env.ip }}" # Only run if the IP has changed

    steps:
      - name: Get Public IP Address
        id: get_ip
        run: |
          PUBLIC_IP=$(curl -s https://api.ipify.org)
          echo "ip=$PUBLIC_IP" >> $GITHUB_ENV
          echo "Public IP is $PUBLIC_IP"

      - name: Update Cloudflare DNS
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_RECORD_ID: ${{ secrets.CF_RECORD_ID }}
          CF_DOMAIN: "your.domain.com" # Replace with your domain
          PUBLIC_IP: ${{ env.ip }}
        run: |
          echo "Updating DNS record for $CF_DOMAIN to $PUBLIC_IP"
          curl -X PUT "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$CF_RECORD_ID" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "type": "A",
            "name": "'"$CF_DOMAIN"'",
            "content": "'"$PUBLIC_IP"'",
            "ttl": 120,
            "proxied": false
          }' | jq .

      - name: Update LAST_KNOWN_IP secret
        run: |
          echo "Updating LAST_KNOWN_IP secret"
          gh secret set LAST_KNOWN_IP --body "${{ env.ip }}"
